# Midterm 1: run the data generator in Colab

Use this notebook if you cannot run Python or git on your own machine. It only **generates and shows your data**. You write your answers in `ANSWERS.md` on **your fork on github.com** (open the file, click the pencil icon, edit, *Commit changes*), then submit the commit URL in Canvas. See the README for the rules.

1. Fill in `GITHUB_USERNAME` (the account that owns your fork) and `CODE` (`PRACTICE` to rehearse; the real code is on the board during the exam).
2. Run the three code cells in order.

In [2]:
GITHUB_USERNAME = "kaelowz"
CODE = "KETTLE-62"      # replace with the session code during the exam
assert GITHUB_USERNAME, "fill in GITHUB_USERNAME first"

In [3]:
import os

if not os.path.exists("midterm-1-AI-course"):
    !git clone --quiet https://github.com/unreal-kz/midterm-1-AI-course.git
%cd midterm-1-AI-course
!python make_my_data.py --github {GITHUB_USERNAME} --code {CODE}

/content/midterm-1-AI-course
Wrote 3 files to my_data/ · fingerprint 3f5ba607
Next: open my_data/DATA.md

In [4]:
import pandas as pd
from IPython.display import Markdown, display

display(Markdown(open("my_data/DATA.md", encoding="utf-8").read()))
ranks = pd.read_csv("my_data/retrieval_ranks.csv")   # Part 1
docs = pd.read_csv("my_data/doc_results.csv")        # Part 2
display(ranks.head(), docs)

# Midterm 1: your data

GitHub username: `kaelowz` · session code: `kettle-62` · generator v1

**Fingerprint: `3f5ba607`**: copy it into the first lines of `ANSWERS.md`. All numbers below are synthetic: this is an exam, not a measurement.

## Part 1: inputs

`retrieval_ranks.csv`: 60 test questions (20 EN, 20 RU, 20 KK). `rank_A` and `rank_B` give the position of the correct chunk in the top 10 retrieved under config A and config B; **11 means the correct chunk was not in the top 10.**

Production traffic and Model M token counts (tokens per item, as counted by Model M's tokenizer):

| language | share of traffic | question tokens | answer tokens | chunk A tokens | chunk B tokens |
|---|---|---|---|---|---|
| EN | 41 % | 36 | 133 | 269 | 67 |
| RU | 43 % | 72 | 266 | 538 | 134 |
| KK | 16 % | 132 | 488 | 987 | 246 |

- Requests per day: **12,500**, in the traffic shares above.
- System prompt: **247** tokens in every request.
- Price: **$2.5** per million input tokens, **$15** per million output tokens.
- Annual budget for this service (model calls only): **$32,600**.

## Part 2: inputs

`doc_results.csv`: for each pipeline, language and scan condition, `n_docs` test invoices and `n_correct` = invoices whose number, date, seller ID and total were all extracted exactly (strict scorer, as in Lab 04).

- **Pipeline H**: hosted vision-language API in a data centre abroad, pay per token; each page is sent as an image.
- **Pipeline L**: open vision-language model on your own server in Kazakhstan, fixed monthly cost.

- Volume: **5,000** scanned pages per day. In **16 %** of them an individual's name and ИИН are printed (sole proprietors, receipts).
- Page image: **1240 × 1754** pixels. Pipeline H counts an image as ⌈width ÷ 28⌉ × ⌈height ÷ 28⌉ input tokens and returns about **367** output tokens per page (the JSON).
- Pipeline H price: **$3** per million input tokens, **$15** per million output tokens.
- Pipeline L: one server costs **$450** per month and handles up to **8,000** pages per day; add servers as needed.

## Part 3: your five questions

Answer each in `ANSWERS.md`: one **Number** line and one **Why** line of at most 40 words.

### Q1

One complaint sentence, measured three ways (synthetic numbers):

| | characters | UTF-8 bytes | tokens (Model M) |
|---|---|---|---|
| EN | 294 | 294 | 55 |
| RU | 325 | 634 | 110 |
| KK | 318 | 628 | 202 |

Compute the KK÷EN ratio for characters, for bytes and for tokens. **Number:** the token ratio divided by the byte ratio (2 decimals). **Why** (at most 40 words): what does this number say about where the Kazakh premium comes from, the encoding or the tokenizer?

### Q2

A teammate sets the chunk size to **768 tokens, counted with cl100k**. The retrieval model (e5-small) reads at most 512 of *its own* tokens. Assume e5 tokens grow in proportion to cl100k tokens at the rate measured in Lecture 4.1 (a chunker told 256 cl100k tokens produced chunks of 263 / 128 / 76 e5 tokens for EN / RU / KK), and that every chunk is exactly the full size.

**Number:** the share of an English chunk, in percent (1 decimal), that the embedding never sees. **Why** (at most 40 words): which of the three languages are cut, and what happens to the cut part?

### Q3

A language model gives these next-token scores for the prompt "The branch is closed on":

| token | score |
|---|---|
| Monday | 4.1 |
| Friday | 3.7 |
| Sunday | 3.3 |
| holiday | 2.1 |
| Easter | 1.6 |

Apply softmax at temperature T = 2. **Number:** the probability of the top token, in percent (1 decimal). **Why** (at most 40 words): what did changing T do to the ranking of the tokens, and to the set of tokens that can be sampled?

### Q4

Two models answer the same 100 factual questions (1 point per correct answer on the public leaderboard):

| | correct | wrong | "I don't know" |
|---|---|---|---|
| Model X | 71 | 29 | 0 |
| Model Y | 65 | 18 | 17 |

Now score them again with a penalty: +1 per correct answer, −2 per wrong answer, 0 for "I don't know". **Number:** Y's penalised score minus X's (negative if X is ahead). **Why** (at most 40 words): which model does the public leaderboard prefer, and what does that teach a model to do?

### Q5

A lab trains a model with **70 billion parameters on 3.43 trillion tokens**. Chinchilla (Lecture 1.1) trained 70 billion parameters on 1.4 trillion tokens, which the paper presents as the compute-optimal ratio. **Number:** this model's tokens per parameter divided by Chinchilla's tokens per parameter (2 decimals). **Why** (at most 40 words): is the model under- or over-trained by that criterion, and what did Chinchilla say about models such as GPT-3?

   qid lang  rank_A  rank_B
0  q01   KK      11      11
1  q02   RU      11      11
2  q03   RU      11      11
3  q04   KK       1       1
4  q05   RU       1       1

   pipeline lang condition  n_docs  n_correct
0         H   EN     clean      30         29
1         H   EN  degraded      30         26
2         H   RU     clean      30         27
3         H   RU  degraded      30         25
4         H   KK     clean      30         25
5         H   KK  degraded      30         24
6         L   EN     clean      30         29
7         L   EN  degraded      30         25
8         L   RU     clean      30         28
9         L   RU  degraded      30         23
10        L   KK     clean      30         21
11        L   KK  degraded      30         22

`ranks` and `docs` are ready for you to compute with. Remember the **fingerprint** at the top of the data sheet: it goes into the first lines of `ANSWERS.md`.

In [7]:
ranks.head(5)

   qid lang  rank_A  rank_B
0  q01   KK      11      11
1  q02   RU      11      11
2  q03   RU      11      11
3  q04   KK       1       1
4  q05   RU       1       1

In [8]:
docs.head(5)

  pipeline lang condition  n_docs  n_correct
0        H   EN     clean      30         29
1        H   EN  degraded      30         26
2        H   RU     clean      30         27
3        H   RU  degraded      30         25
4        H   KK     clean      30         25

In [9]:
!python make_my_data.py --github kaelowz --code KETTLE-62
!cat my_data/DATA.md

Wrote 3 files to my_data/ · fingerprint 3f5ba607
Next: open my_data/DATA.md
# Midterm 1: your data

GitHub username: `kaelowz` · session code: `kettle-62` · generator v1

**Fingerprint: `3f5ba607`**: copy it into the first lines of `ANSWERS.md`. All numbers below are synthetic: this is an exam, not a measurement.

## Part 1: inputs

`retrieval_ranks.csv`: 60 test questions (20 EN, 20 RU, 20 KK). `rank_A` and `rank_B` give the position of the correct chunk in the top 10 retrieved under config A and config B; **11 means the correct chunk was not in the top 10.**

Production traffic and Model M token counts (tokens per item, as counted by Model M's tokenizer):

| language | share of traffic | question tokens | answer tokens | chunk A tokens | chunk B tokens |
|---|---|---|---|---|---|
| EN | 41 % | 36 | 133 | 269 | 67 |
| RU | 43 % | 72 | 266 | 538 | 134 |
| KK | 16 % | 132 | 488 | 987 | 246 |

- Requests per day: **12,500**, in the traffic shares above.
- System prompt: **247** tokens in every request.
- Price: **$2.5** per million input tokens, **$15** per million output tokens.
- Annual budget for this service (model calls only): **$32,600**.

## Part 2: inputs

`doc_results.csv`: for each pipeline, language and scan condition, `n_docs` test invoices and `n_correct` = invoices whose number, date, seller ID and total were all extracted exactly (strict scorer, as in Lab 04).

- **Pipeline H**: hosted vision-language API in a data centre abroad, pay per token; each page is sent as an image.
- **Pipeline L**: open vision-language model on your own server in Kazakhstan, fixed monthly cost.

- Volume: **5,000** scanned pages per day. In **16 %** of them an individual's name and ИИН are printed (sole proprietors, receipts).
- Page image: **1240 × 1754** pixels. Pipeline H counts an image as ⌈width ÷ 28⌉ × ⌈height ÷ 28⌉ input tokens and returns about **367** output tokens per page (the JSON).
- Pipeline H price: **$3** per million input tokens, **$15** per million output tokens.
- Pipeline L: one server costs **$450** per month and handles up to **8,000** pages per day; add servers as needed.

## Part 3: your five questions

Answer each in `ANSWERS.md`: one **Number** line and one **Why** line of at most 40 words.

### Q1

One complaint sentence, measured three ways (synthetic numbers):

| | characters | UTF-8 bytes | tokens (Model M) |
|---|---|---|---|
| EN | 294 | 294 | 55 |
| RU | 325 | 634 | 110 |
| KK | 318 | 628 | 202 |

Compute the KK÷EN ratio for characters, for bytes and for tokens. **Number:** the token ratio divided by the byte ratio (2 decimals). **Why** (at most 40 words): what does this number say about where the Kazakh premium comes from, the encoding or the tokenizer?

### Q2

A teammate sets the chunk size to **768 tokens, counted with cl100k**. The retrieval model (e5-small) reads at most 512 of *its own* tokens. Assume e5 tokens grow in proportion to cl100k tokens at the rate measured in Lecture 4.1 (a chunker told 256 cl100k tokens produced chunks of 263 / 128 / 76 e5 tokens for EN / RU / KK), and that every chunk is exactly the full size.

**Number:** the share of an English chunk, in percent (1 decimal), that the embedding never sees. **Why** (at most 40 words): which of the three languages are cut, and what happens to the cut part?

### Q3

A language model gives these next-token scores for the prompt "The branch is closed on":

| token | score |
|---|---|
| Monday | 4.1 |
| Friday | 3.7 |
| Sunday | 3.3 |
| holiday | 2.1 |
| Easter | 1.6 |

Apply softmax at temperature T = 2. **Number:** the probability of the top token, in percent (1 decimal). **Why** (at most 40 words): what did changing T do to the ranking of the tokens, and to the set of tokens that can be sampled?

### Q4

Two models answer the same 100 factual questions (1 point per correct answer on the public leaderboard):

| | correct | wrong | "I don't know" |
|---|---|---|---|
| Model X | 71 | 29 | 0 |
| Model Y | 65 | 18 | 17 |

Now score them again with a penalty: +1 per correct answer, −2 per wrong answer, 0 for "I don't know". **Number:** Y's penalised score minus X's (negative if X is ahead). **Why** (at most 40 words): which model does the public leaderboard prefer, and what does that teach a model to do?

### Q5

A lab trains a model with **70 billion parameters on 3.43 trillion tokens**. Chinchilla (Lecture 1.1) trained 70 billion parameters on 1.4 trillion tokens, which the paper presents as the compute-optimal ratio. **Number:** this model's tokens per parameter divided by Chinchilla's tokens per parameter (2 decimals). **Why** (at most 40 words): is the model under- or over-trained by that criterion, and what did Chinchilla say about models such as GPT-3?

In [10]:

!git clone https://github.com/kaelowz/midterm-1-AI-course.git 2>/dev/null || echo "Repository already cloned"

import os
os.chdir('midterm-1-AI-course')

github_username = "kaelowz"
session_code = "kettle-62"

print(f"Generating data for username: {github_username}, session code: {session_code}")
!python make_my_data.py --github {github_username} --code {session_code}

print("\nFiles inside my_data folder:")
print(os.listdir('my_data'))

print("\n--- First lines of your DATA.md ---")
with open('my_data/DATA.md', 'r', encoding='utf-8') as f:
    lines = [f.readline() for _ in range(15)]
    print("".join(lines))

Generating data for username: kaelowz, session code: kettle-62
Wrote 3 files to my_data/ · fingerprint 3f5ba607
Next: open my_data/DATA.md

Files inside my_data folder:
['doc_results.csv', 'DATA.md', 'retrieval_ranks.csv']

--- First lines of your DATA.md ---
# Midterm 1: your data

GitHub username: `kaelowz` · session code: `kettle-62` · generator v1

**Fingerprint: `3f5ba607`**: copy it into the first lines of `ANSWERS.md`. All numbers below are synthetic: this is an exam, not a measurement.

## Part 1: inputs

`retrieval_ranks.csv`: 60 test questions (20 EN, 20 RU, 20 KK). `rank_A` and `rank_B` give the position of the correct chunk in the top 10 retrieved under config A and config B; **11 means the correct chunk was not in the top 10.**

Production traffic and Model M token counts (tokens per item, as counted by Model M's tokenizer):

| language | share of traffic | question tokens | answer tokens | chunk A tokens | chunk B tokens |
|---|---|---|---|---|---|
| EN | 41 % | 36 | 133 | 269 | 67 |

In [11]:
import math
import pandas as pd

# Global settings and constants
Z = 1.96
LANGS = ["EN", "RU", "KK"]
CANDIDATES = [("A", 3), ("A", 5), ("B", 3), ("B", 5)]
RANKS_CSV = "my_data/retrieval_ranks.csv"  # Path to retrieval ranks CSV file in Colab
DOCS_CSV = "my_data/doc_results.csv"      # Path to document results CSV file in Colab

def wilson(hits, n, z=Z):
    """Calculate the 95% Wilson score interval for a proportion."""
    p = hits / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return max(0.0, centre - half), min(1.0, centre + half)

def fmt_ci(hits, n):
    """Format proportion and Wilson confidence interval as a string."""
    lo, hi = wilson(hits, n)
    return f"{hits}/{n} = {hits / n:.3f} [{lo:.3f}, {hi:.3f}]"

def mrr10(ranks):
    """Calculate Mean Reciprocal Rank at k=10."""
    return sum(1 / r for r in ranks if r <= 10) / len(ranks)

In [12]:
P = dict(
    share={"EN": 41, "RU": 43, "KK": 16},            # Traffic share percentage
    q_tok={"EN": 36, "RU": 72, "KK": 132},          # Question tokens per language
    a_tok={"EN": 133, "RU": 266, "KK": 488},        # Answer tokens per language
    chunk={"A": {"EN": 269, "RU": 538, "KK": 987},
           "B": {"EN": 67, "RU": 134, "KK": 246}},   # Chunk tokens per config and language
    system=247, rpd=12500, p_in=2.5, p_out=15, budget=32600,
)
Q = dict(pages_day=5000, pii=16, w=1240, h=1754, out_tok=367,
         p_in=3, p_out=15, srv_month=450, srv_cap=8000)

In [13]:
def annual_cost(cfg, k):
    """Calculate the annual cost of model calls for a given chunking config and k."""
    per_request = 0.0
    for lang in LANGS:
        tokens_in = P["system"] + P["q_tok"][lang] + k * P["chunk"][cfg][lang]
        cost = (tokens_in * P["p_in"] + P["a_tok"][lang] * P["p_out"]) / 1e6
        per_request += P["share"][lang] / 100 * cost
    return per_request * P["rpd"] * 365

In [14]:
ranks = pd.read_csv(RANKS_CSV)
N = len(ranks)

print("=== 1a: Recall@k and MRR@10 ===")
rows = []
for cfg in "AB":
    col = ranks[f"rank_{cfg}"]
    rows.append({"config": cfg,
                 **{f"recall@{k}": round((col <= k).sum() / N, 3) for k in (1, 3, 5)},
                 "MRR@10": round(mrr10(col), 4)})
print(pd.DataFrame(rows).to_string(index=False))

print("\n=== 1b + 1c: Intervals and Annual Cost ===")
cands = []
for cfg, k in CANDIDATES:
    hits = int((ranks[f"rank_{cfg}"] <= k).sum())
    lo, hi = wilson(hits, N)
    cost = annual_cost(cfg, k)
    cands.append(dict(cfg=cfg, k=k, hits=hits, lo=lo, hi=hi, cost=cost,
                      ok=cost <= P["budget"]))
table = pd.DataFrame(cands)
table["recall"] = (table.hits / N).round(3)
table["CI95"] = table.apply(lambda r: f"[{r.lo:.3f}, {r.hi:.3f}]", axis=1)
table["cost_$"] = table.cost.round(0).astype(int)
table["in_budget"] = table.ok
print(table[["cfg", "k", "hits", "recall", "CI95", "cost_$", "in_budget"]].to_string(index=False))
print(f"Budget Limit: ${P['budget']:,}")

print("\n=== 1d: Decision & Selection ===")
affordable = [c for c in cands if c["ok"]]
best = max(affordable, key=lambda c: (c["hits"], -c["cost"]))
pool = [c for c in affordable if c["lo"] <= best["hi"] and best["lo"] <= c["hi"]]
choice = min(pool, key=lambda c: c["cost"])
print(f"Best recall within budget: ({best['cfg']}, {best['k']})")
print("Statistically indistinguishable from best (overlapping intervals):",
      [(c["cfg"], c["k"]) for c in pool])
print(f"Selected candidate (cheapest of the pool): ({choice['cfg']}, {choice['k']}), "
      f"${choice['cost']:,.0f}, budget surplus ${P['budget'] - choice['cost']:,.0f}")

print(f"\nPer-language recall for selected candidate ({choice['cfg']}, {choice['k']}):")
col = f"rank_{choice['cfg']}"
for lang in LANGS:
    sub = ranks[ranks.lang == lang]
    print(f"  {lang}: {fmt_ci(int((sub[col] <= choice['k']).sum()), len(sub))}")

=== 1a: Recall@k and MRR@10 ===
config  recall@1  recall@3  recall@5  MRR@10
     A     0.533     0.650     0.683  0.5869
     B     0.483     0.617     0.700  0.5739

=== 1b + 1c: Intervals and Annual Cost ===
cfg  k  hits  recall           CI95  cost_$  in_budget
  A  3    39   0.650 [0.524, 0.758]   37577      False
  A  5    41   0.683 [0.558, 0.787]   48973      False
  B  3    37   0.617 [0.490, 0.729]   24742       True
  B  5    42   0.700 [0.575, 0.801]   27581       True
Budget Limit: $32,600

=== 1d: Decision & Selection ===
Best recall within budget: (B, 5)
Statistically indistinguishable from best (overlapping intervals): [('B', 3), ('B', 5)]
Selected candidate (cheapest of the pool): (B, 3), $24,742, budget surplus $7,858

Per-language recall for selected candidate (B, 3):
  EN: 14/20 = 0.700 [0.481, 0.855]
  RU: 12/20 = 0.600 [0.387, 0.781]
  KK: 11/20 = 0.550 [0.342, 0.742]

In [15]:
docs = pd.read_csv(DOCS_CSV)
docs["acc"] = docs.n_correct / docs.n_docs

print("\n=== 2a: Pipeline Accuracy & Cost ===")
img_tokens = math.ceil(Q["w"] / 28) * math.ceil(Q["h"] / 28)
cost_pipe = {
    "H": Q["pages_day"] * 365 * (img_tokens * Q["p_in"] + Q["out_tok"] * Q["p_out"]) / 1e6,
    "L": math.ceil(Q["pages_day"] / Q["srv_cap"]) * Q["srv_month"] * 12,
}
for pipe in "HL":
    s = docs[docs.pipeline == pipe]
    weakest = s.loc[s.acc.idxmin()]
    print(f"Pipeline {pipe}: overall {fmt_ci(int(s.n_correct.sum()), int(s.n_docs.sum()))}")
    print(f"   weakest cell ({weakest.lang}, {weakest.condition}): "
          f"{fmt_ci(int(weakest.n_correct), int(weakest.n_docs))}")
    print(f"   annual cost: ${cost_pipe[pipe]:,.0f}")
    for lang in LANGS:
        t = s[s.lang == lang]
        print(f"   {lang} (all conditions): {fmt_ci(int(t.n_correct.sum()), int(t.n_docs.sum()))}")

print(f"\nImage tokens per page (Pipeline H): {img_tokens}")
print(f"Pages with PII leaving the country annually under H: "
      f"{Q['pages_day'] * 365 * Q['pii'] / 100:,.0f} pages/year")
print("\nAccuracy pivot table by cell:")
print(docs.pivot_table(index=["lang", "condition"], columns="pipeline", values="acc").round(3))

=== 2a: Pipeline Accuracy & Cost ===
Pipeline H: overall 156/180 = 0.867 [0.809, 0.909]
   weakest cell (KK, degraded): 24/30 = 0.800 [0.627, 0.905]
   annual cost: $25,568
   EN (all conditions): 55/60 = 0.917 [0.819, 0.964]
   RU (all conditions): 52/60 = 0.867 [0.758, 0.931]
   KK (all conditions): 49/60 = 0.817 [0.701, 0.894]
Pipeline L: overall 148/180 = 0.822 [0.760, 0.871]
   weakest cell (KK, clean): 21/30 = 0.700 [0.521, 0.833]
   annual cost: $5,400
   EN (all conditions): 54/60 = 0.900 [0.799, 0.953]
   RU (all conditions): 51/60 = 0.850 [0.739, 0.919]
   KK (all conditions): 43/60 = 0.717 [0.592, 0.815]

Image tokens per page (Pipeline H): 2835
Pages with PII leaving the country annually under H: 292,000 pages/year

Accuracy pivot table by cell:
pipeline            H      L
lang condition
EN   clean      0.967  0.967
     degraded   0.867  0.833
KK   clean      0.833  0.700
     degraded   0.800  0.733
RU   clean      0.900  0.933
     degraded   0.833  0.767